# Generated by Django 3.0.6 on 2020-07-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='portfolio_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
