# Generated by Django 3.0.6 on 2020-07-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='belong_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
