# Generated by Django 3.0.6 on 2020-07-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hacks', '0003_auto_20200715_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_joined', models.BooleanField(default=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hacks',
            name='state',
        ),
        migrations.AddField(
            model_name='hacks',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='chat_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='judge_day',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='judge_line',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='status',
            field=models.CharField(blank=True, choices=[('w', '진행예정(will)'), ('i', '진행(ing)'), ('c', '진행완료(complete)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='is_joined',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='application',
            name='hacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hacks.Hacks'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
