# Generated by Django 3.0.6 on 2020-07-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0004_auto_20200715_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hacks',
            old_name='hacks_rule',
            new_name='rule',
        ),
        migrations.RemoveField(
            model_name='application',
            name='level',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_joined',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_leader',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='complete_level',
            field=models.CharField(default='h', max_length=7),
        ),
        migrations.AddField(
            model_name='application',
            name='is_leader',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hacks.Team'),
        ),
    ]
