# Generated by Django 3.0.6 on 2020-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0005_auto_20200715_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
