# Generated by Django 3.0.6 on 2020-07-15 13:53

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hacks', '0007_hacks_awards_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='hacks',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='application',
            name='complete_level',
        ),
        migrations.RemoveField(
            model_name='team',
            name='max_personnel',
        ),
        migrations.AddField(
            model_name='application',
            name='mission_level',
            field=models.CharField(blank=True, default='h', help_text='[미션 완료 여부]         h:해커톤 참여 신청,        s:슬랙 참여        d:개발링크 제출        v:데모영상 제출         p:기획안 링크 제출         t:팀빌딩 완료         i:아이디어 완료', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.CharField(blank=True, help_text='팀 역할', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hacks',
            name='img',
            field=models.ImageField(blank=True, help_text='해커톤 썸네일', max_length=200, storage=django.core.files.storage.FileSystemStorage(), upload_to='hacks/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='지원일'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_joined',
            field=models.BooleanField(default=False, help_text='팀 가입 여부'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_leader',
            field=models.BooleanField(blank=True, default=False, help_text='리더 여부', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='참가비 지불 여부'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='수정일'),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='awards',
            field=models.TextField(blank=True, help_text='상을 받는 팀(팀의 PK를넘겨주세요      ex) 1,2,3,4    )', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='awards_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='상의 갯수', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='chat_url',
            field=models.CharField(blank=True, help_text='슬랙 URL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='해커톤 생성일'),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='ended_at',
            field=models.DateField(blank=True, help_text='예정일', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='fee',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='참가 비용', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='host',
            field=models.ForeignKey(blank=True, help_text='개최자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='intro',
            field=models.TextField(blank=True, help_text='해커톤 소개', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='judge_day',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='해커톤이 끝나고 며칠 후 까지 심사할 지 1은 1일', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='judge_line',
            field=models.TextField(blank=True, help_text='판단 기준', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='max_personnel',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='최대 참가 인원', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='rule',
            field=models.TextField(blank=True, help_text='해커톤 규칙', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='started_at',
            field=models.DateField(blank=True, help_text='해커톤 시작일', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='status',
            field=models.CharField(blank=True, choices=[('w', '작성(write)'), ('p', '예정(plan)'), ('i', '진행(ing)'), ('c', '완료(complete)')], help_text="해커톤 상태             ('w', '작성(write)'),            ('p', '예정(plan)'),            ('i', '진행(ing)'),            ('c', '완료(complete)')", max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='subject',
            field=models.TextField(blank=True, help_text='해커톤 주제', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='team_personnel',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='팀당 권장 인원', null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='title',
            field=models.CharField(blank=True, help_text='해커톤 이룸', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hacks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='헤커톤 수정일'),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='팀 생성일'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, help_text='팀명', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='팀 수정일'),
        ),
        migrations.AlterField(
            model_name='team',
            name='vote',
            field=models.PositiveIntegerField(default=0, help_text='투표수'),
        ),
    ]
