# Generated by Django 3.0.6 on 2020-07-17 08:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0008_auto_20200715_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacks',
            name='img',
            field=models.ImageField(blank=True, help_text='해커톤 썸네일', max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='hacks/%Y/%m/%d'),
        ),
    ]
