# Generated by Django 3.0.6 on 2020-07-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0010_idea_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_joined',
        ),
        migrations.RemoveField(
            model_name='hacks',
            name='img',
        ),
    ]
