# Generated by Django 3.0.6 on 2020-07-17 20:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0011_auto_20200718_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_joined',
            field=models.BooleanField(default=False, help_text='팀 가입 여부'),
        ),
        migrations.AddField(
            model_name='hacks',
            name='img',
            field=models.ImageField(blank=True, help_text='해커톤 썸네일', max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='hacks/%Y/%m/%d'),
        ),
    ]
