# Generated by Django 3.0.6 on 2020-07-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0013_auto_20200718_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='pitching_url',
            new_name='pitch_url',
        ),
    ]
