# Generated by Django 3.0.6 on 2020-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacks', '0014_auto_20200718_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mission_level',
            field=models.CharField(blank=True, default='-', help_text='[미션 완료 여부]         t:팀 생성 완료        i:아이디어 완료        s:제출 완료', max_length=1, null=True),
        ),
    ]
